// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbUCQI7F5jyZOPsJmzKR6TJoCy7qAiwx0',
    appId: '1:224170307480:android:34b17d15ecbad5838845ed',
    messagingSenderId: '224170307480',
    projectId: 'annisa-furniture',
    storageBucket: 'annisa-furniture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDy5PQsCGpDnkwWCij-9DLoX-JrHxJGdM',
    appId: '1:224170307480:ios:09f4c465b0db6a4e8845ed',
    messagingSenderId: '224170307480',
    projectId: 'annisa-furniture',
    storageBucket: 'annisa-furniture.appspot.com',
    iosClientId: '224170307480-fi97h8f34iau0ukt4e1i8go8lo91njk5.apps.googleusercontent.com',
    iosBundleId: 'com.freedcode.annisaFurniture',
  );
}
